detectors:
  DuplicateMethodCall:
    exclude:
      - ArtDecomp::KISSDecomposerBehaviour
      - ArtDecomp::PutBehaviour
    max_calls: 2

  IrresponsibleModule:
    enabled: false

  NestedIterators:
    max_allowed_nesting: 2

  TooManyStatements:
    exclude:
      - ArtDecomp::KISSDecomposerBehaviour
      - ArtDecomp::PutBehaviour

  UncommunicativeVariableName:
    accept:
      - a
      - b
      - c
