Lint/UnusedMethodArgument:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - test/art_decomp/*_behaviour.rb

Metrics/MethodLength:
  Exclude:
    - test/art_decomp/*_behaviour.rb

Performance/ParallelAssignment:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Not:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SpaceAfterComma:
  Enabled: false

Style/TrailingComma:
  EnforcedStyleForMultiline: comma
