Lint/UnusedMethodArgument:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Not:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Style/SpaceAfterComma:
  Enabled: false

Style/TrailingComma:
  EnforcedStyleForMultiline: comma
