AllCops:
  Exclude:
    - tmp/**/*

Metrics/AbcSize:
  Exclude:
    - test/art_decomp/*_behaviour.rb

Metrics/BlockLength:
  Exclude:
    - test/**/*.rb

Metrics/MethodLength:
  Exclude:
    - test/art_decomp/*_behaviour.rb

Metrics/ModuleLength:
  Exclude:
    - test/**/*.rb

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/Not:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
