AbcSize:
  Exclude:
    - lib/art_decomp/arch_sizer.rb
    - lib/art_decomp/seps.rb

AndOr:
  Enabled: false

Documentation:
  Enabled: false

Not:
  Enabled: false

ParameterLists:
  Exclude:
    - lib/art_decomp/circuit.rb

PredicateName:
  Exclude:
    - lib/art_decomp/circuit.rb
    - lib/art_decomp/function_decomposer/parallel.rb

SingleLineBlockParams:
  Enabled: false

SingleSpaceBeforeFirstArg:
  Enabled: false

SpaceAfterComma:
  Enabled: false

TrailingComma:
  EnforcedStyleForMultiline: comma

UnusedMethodArgument:
  Enabled: false
