AllCops:
  Exclude:
    - tmp/**/*

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - test/art_decomp/*_behaviour.rb

Metrics/MethodLength:
  Exclude:
    - test/art_decomp/*_behaviour.rb

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ExtraSpacing:
  Enabled: false

Style/Not:
  Enabled: false

Style/ParallelAssignment:
  Exclude:
    - test/**/*

Style/SingleLineBlockParams:
  Enabled: false

Style/SpaceAfterComma:
  Exclude:
    - test/**/*

Style/TrailingComma:
  EnforcedStyleForMultiline: comma
