AccessControl:
  Enabled: false

AndOr:
  Enabled: false

BlockAlignment:
  Enabled: false

ConstantName:
  Enabled: false

DefWithoutParentheses:
  Enabled: false

Documentation:
  Enabled: false

EndAlignment:
  Enabled: false

HashSyntax:
  Enabled: false

Not:
  Enabled: false

ParameterLists:
  Enabled: false

ReduceArguments:
  Enabled: false

RegexpLiteral:
  Enabled: false

SpaceAfterComma:
  Enabled: false

SpaceAroundOperators:
  Enabled: false

UselessComparison:
  Enabled: false
