Lint/UnusedMethodArgument:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - lib/art_decomp/arch_sizer.rb
    - lib/art_decomp/seps.rb

Metrics/ParameterLists:
  Exclude:
    - lib/art_decomp/circuit.rb

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Not:
  Enabled: false

Style/PredicateName:
  Exclude:
    - lib/art_decomp/circuit.rb
    - lib/art_decomp/function_decomposer/parallel.rb

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Style/SpaceAfterComma:
  Enabled: false

Style/TrailingComma:
  EnforcedStyleForMultiline: comma
