Lint/UnusedMethodArgument:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - test/art_decomp/seps_test.rb

Performance/ParallelAssignment:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Not:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SpaceAfterComma:
  Enabled: false

Style/TrailingComma:
  EnforcedStyleForMultiline: comma
