AccessModifierIndentation:
  Enabled: false

AlignHash:
  Enabled: false

AndOr:
  Enabled: false

ConstantName:
  Enabled: false

Documentation:
  Enabled: false

EndAlignment:
  Enabled: false

IndentationWidth:
  Enabled: false

MethodDefParentheses:
  Enabled: false

Not:
  Enabled: false

SingleLineBlockParams:
  Enabled: false

SpaceAfterComma:
  Enabled: false

SpaceAroundOperators:
  Enabled: false

TrailingComma:
  Enabled: false

UselessComparison:
  Enabled: false
