AccessModifierIndentation:
  Enabled: false

AlignHash:
  Enabled: false

AndOr:
  Enabled: false

ConstantName:
  Enabled: false

DefWithoutParentheses:
  Enabled: false

Documentation:
  Enabled: false

EndAlignment:
  Enabled: false

IndentationWidth:
  Enabled: false

Not:
  Enabled: false

ParameterLists:
  Enabled: false

ReduceArguments:
  Enabled: false

SignalException:
  Enabled: false

SpaceAfterComma:
  Enabled: false

SpaceAroundOperators:
  Enabled: false

UselessComparison:
  Enabled: false
