AbcSize:
  Exclude:
    - lib/art_decomp/arch_sizer.rb

AndOr:
  Enabled: false

Documentation:
  Enabled: false

Not:
  Enabled: false

PredicateName:
  Exclude:
    - lib/art_decomp/circuit.rb

SingleLineBlockParams:
  Enabled: false

SingleSpaceBeforeFirstArg:
  Enabled: false

SpaceAfterComma:
  Enabled: false

TrailingComma:
  EnforcedStyleForMultiline: comma

UnusedMethodArgument:
  Enabled: false
