AllCops:
  Exclude:
    - tmp/**/*
  TargetRubyVersion: 2.3

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - test/art_decomp/*_behaviour.rb

Metrics/MethodLength:
  Exclude:
    - test/art_decomp/*_behaviour.rb

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Not:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
