AndOr:
  Enabled: false

Documentation:
  Enabled: false

MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Not:
  Enabled: false

SingleLineBlockParams:
  Enabled: false

SingleSpaceBeforeFirstArg:
  Enabled: false

SpaceAfterComma:
  Enabled: false

TrailingComma:
  EnforcedStyleForMultiline: comma
