AndOr:
  Enabled: false

Documentation:
  Enabled: false

Not:
  Enabled: false

SingleLineBlockParams:
  Enabled: false

SingleSpaceBeforeFirstArg:
  Enabled: false

SpaceAfterComma:
  Enabled: false

TrailingComma:
  EnforcedStyleForMultiline: comma

UnusedMethodArgument:
  Enabled: false
