require 'delegate'

require_relative 'art_decomp/arch'
require_relative 'art_decomp/arch_sizer'
require_relative 'art_decomp/b'
require_relative 'art_decomp/circuit'
require_relative 'art_decomp/circuit_decomposer'
require_relative 'art_decomp/circuit_presenter'
require_relative 'art_decomp/circuit_solder'
require_relative 'art_decomp/decompositions'
require_relative 'art_decomp/function'
require_relative 'art_decomp/function_decomposer'
require_relative 'art_decomp/function_presenter'
require_relative 'art_decomp/kiss_decomposer'
require_relative 'art_decomp/kiss_parser'
require_relative 'art_decomp/put'
require_relative 'art_decomp/wire'
