DuplicateMethodCall:
  exclude:
    - ArtDecomp::ArchSizer#min_quarters
    - ArtDecomp::Circuit#self.from_fsm
    - ArtDecomp::CircuitPresenter#wiring_for
    - ArtDecomp::CircuitSizer::ArchSizer#min_quarters
    - ArtDecomp::FunctionDecomposer#self.decompose
    - ArtDecomp::FunctionSimplifier#is_required_for
    - ArtDecomp::FunctionSimplifier#required_is
    - ArtDecomp::KISSDecomposer#decompose
    - ArtDecomp::KISSParser#putify
    - ArtDecomp::Put#self.from_column

IrresponsibleModule:
  enabled: false

NestedIterators:
  max_allowed_nesting: 2

TooManyStatements:
  exclude:
    - ArtDecomp::ArchSizer#max_quarters
    - ArtDecomp::Seps#inspect
    - ArtDecomp::Seps#self.from_blocks

UncommunicativeModuleName:
  exclude:
    - ArtDecomp::B

UncommunicativeParameterName:
  exclude:
    - ArtDecomp::CircuitPresenter#wiring_for

UncommunicativeVariableName:
  exclude:
    - ArtDecomp::CircuitPresenter#wirings_for
    - ArtDecomp::FunctionSimplifier#simplify
    - ArtDecomp::FunctionSimplifier#take_required
    - ArtDecomp::Seps#|
