DuplicateMethodCall:
  exclude:
    - ArtDecomp::ArchSizer#min_quarters
    - ArtDecomp::FunctionDecomposer#self.decompose
    - ArtDecomp::Put#self.from_column

IrresponsibleModule:
  enabled: false

LongParameterList:
  exclude:
    - ArtDecomp::Circuit#initialize
    - ArtDecomp::Circuit#self.from_fsm

NestedIterators:
  max_allowed_nesting: 2

TooManyInstanceVariables:
  exclude:
    - ArtDecomp::Circuit

TooManyStatements:
  exclude:
    - ArtDecomp::ArchSizer#max_quarters
    - ArtDecomp::Seps#inspect
    - ArtDecomp::Seps#self.from_blocks

UncommunicativeModuleName:
  exclude:
    - ArtDecomp::B

UncommunicativeParameterName:
  exclude:
    - ArtDecomp::PinPresenter#label

UncommunicativeVariableName:
  exclude:
    - ArtDecomp::Circuit#is_wires
    - ArtDecomp::Circuit#os_wires
    - ArtDecomp::FunctionDecomposer::Parallel#decompositions
    - ArtDecomp::FunctionDecomposer::Parallel#merged
    - ArtDecomp::KISSDecomposer#decompose
    - ArtDecomp::PinPresenter#labels
    - ArtDecomp::Put#self.from_column
    - ArtDecomp::RequiredPutsFilter#initialize
    - ArtDecomp::Seps#&
    - ArtDecomp::Seps#-
    - ArtDecomp::Seps#inspect
    - ArtDecomp::Seps#|
