DuplicateMethodCall:
  exclude:
    - ArtDecomp::ArchSizer#min_quarters
    - ArtDecomp::Circuit#self.from_fsm
    - ArtDecomp::CircuitSizer::ArchSizer#min_quarters
    - ArtDecomp::FunctionDecomposer#self.decompose
    - ArtDecomp::FunctionSimplifier#is_required_for
    - ArtDecomp::FunctionSimplifier#required_is
    - ArtDecomp::KISSDecomposer#decompose
    - ArtDecomp::KISSParser#putify
    - ArtDecomp::Put#self.from_column

IrresponsibleModule:
  enabled: false

LongParameterList:
  exclude:
    - ArtDecomp::Circuit#initialize
    - ArtDecomp::Circuit#self.from_fsm

NestedIterators:
  max_allowed_nesting: 2

TooManyInstanceVariables:
  exclude:
    - ArtDecomp::Circuit

TooManyStatements:
  exclude:
    - ArtDecomp::ArchSizer#max_quarters
    - ArtDecomp::Seps#inspect
    - ArtDecomp::Seps#self.from_blocks

UncommunicativeModuleName:
  exclude:
    - ArtDecomp::B

UncommunicativeParameterName:
  exclude:
    - ArtDecomp::PinPresenter#label

UncommunicativeVariableName:
  exclude:
    - ArtDecomp::Seps#|
